site_name: 《普通地质学》考研笔记

site_url: https://geo.barku.re

repo_url: https://github.com/barkure/Physical-Geology-Notes

repo_name: Physical-Geology-Notes

site_author: barkure

copyright: © 2024 barkure

theme:
  name: material
  language: zh
  palette: 
  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/weather-night
      name: 切换到暗色模式

  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: 切换到亮色模式

extra:
  # generator: false  #删除页脚显示“使用 MkDocs 材料制造”
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/barkure
        name: GitHub
      - icon: simple/hexo
        link: https://barku.re
        name: Bilibili
      - icon: material/email
        link: mailto:xinyao_qi@outlook.com
        name: Email

features:
  - navigation.instant

nav:
  - 首页: index.md
  - 1.地球的一般概念及特征（10'）: 1.地球的一般概念及特征.md
  - 2.地球的物质组成（10'）: 2.地球的物质组成.md
  - 3.内力地质作用的一般特征（10'）: 3.内力地质作用的一般特征.md
  - 4.外力地质作用的一般特征（10'）: 4.外力地质作用的一般特征.md
  - 5.地质构造的基本概念（10'）: 5.地质构造的基本概念.md
  - 6.地质年代的涵义及其确定方法（12'）: 6.地质年代的涵义及其确定方法.md
  - 7.常见的地质灾害（8'）: 7.常见的地质灾害.md
  - 8.地质图构成与识图（10'）: 8.地质图构成与识图.md
  - 补充内容: 补充内容.md